# Generated by Django 4.1.7 on 2023-04-12 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('symbol', models.CharField(max_length=200)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('last_day_percent_change', models.CharField(blank=True, max_length=200, null=True)),
                ('last_day_lowest_price', models.FloatField(blank=True, null=True)),
                ('last_day_highest_price', models.FloatField(blank=True, null=True)),
                ('last_day_open_price', models.FloatField(blank=True, null=True)),
                ('all_time_highest_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
