# Generated by Django 4.1.7 on 2023-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='last_day_percent_change',
        ),
        migrations.AddField(
            model_name='currency',
            name='percent_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
