# Generated by Django 4.1.7 on 2023-05-21 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0002_remove_currency_last_day_percent_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
